// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "홍정완",
            "email": "test@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applicants": {
            "get": {
                "description": "지원자 목록과 총 개수를 조회한다.",
                "tags": [
                    "Applicants"
                ],
                "summary": "지원자 목록 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "페이지 번호",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "페이지당 항목 수",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "단계 필터 (서류 접수, 기술 면접…)",
                        "name": "stage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "이름 또는 이메일 키워드 검색",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.ListApplicantsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/applicants/stages/bulk-update": {
            "post": {
                "description": "여러 지원자의 전형 단계를 일괄 수정한다.",
                "tags": [
                    "Applicants"
                ],
                "summary": "지원자 단계 일괄 업데이트",
                "parameters": [
                    {
                        "description": "일괄 업데이트 요청",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_request.BulkUpdateStageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.BulkUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/applicants/{application_id}": {
            "get": {
                "description": "단일 지원자 정보를 조회한다.",
                "tags": [
                    "Applicants"
                ],
                "summary": "지원자 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "지원자 식별자",
                        "name": "application_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.ApplicantDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/applicants/{application_id}/history": {
            "get": {
                "description": "해당 지원자의 전형 단계 변경 이력을 조회한다.",
                "tags": [
                    "Applicants"
                ],
                "summary": "지원자 단계 변경 이력 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "지원자 식별자",
                        "name": "application_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.StageHistoryItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/applicants/{application_id}/stage": {
            "patch": {
                "description": "지원자 전형 단계를 수정한다.",
                "tags": [
                    "Applicants"
                ],
                "summary": "지원자 단계 업데이트",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "지원자 식별자",
                        "name": "application_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "업데이트할 단계 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_request.UpdateStageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.UpdateStageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "로그인 아이디와 비밀번호로 인증하고 세션을 생성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "사용자 로그인",
                "parameters": [
                    {
                        "description": "로그인 정보",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_user_dto_request.Credentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message와 user_id 반환",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "현재 세션을 파괴하여 로그아웃한다.",
                "tags": [
                    "Auth"
                ],
                "summary": "사용자 로그아웃",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/email-history": {
            "get": {
                "description": "이메일 발송 이력 목록과 페이징 정보를 반환한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EmailHistory"
                ],
                "summary": "이메일 발송 이력 목록 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "지원자 식별자",
                        "name": "applicant_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "오퍼 식별자",
                        "name": "offer_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "페이지 번호",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "페이지당 목록 수",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailHistoryItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "이메일 발송 이력 레코드를 생성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EmailHistory"
                ],
                "summary": "이메일 발송 이력 생성",
                "parameters": [
                    {
                        "description": "이메일 발송 요청",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_request.CreateEmailHistory"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.CreateEmailHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/email-history/{email_id}": {
            "get": {
                "description": "특정 이메일 발송 이력의 상세 정보를 반환한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EmailHistory"
                ],
                "summary": "이메일 발송 이력 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "이메일 이력 식별자",
                        "name": "email_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailHistoryDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/email-templates": {
            "get": {
                "description": "저장된 모든 이메일 템플릿의 정보를 반환한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EmailTemplates"
                ],
                "summary": "이메일 템플릿 목록 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailTemplateItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "새로운 이메일 템플릿을 생성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EmailTemplates"
                ],
                "summary": "이메일 템플릿 생성",
                "parameters": [
                    {
                        "description": "생성할 템플릿 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_request.CreateEmailTemplate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailTemplateDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/email-templates/{template_id}": {
            "get": {
                "description": "선택된 이메일 템플릿의 상세 정보를 반환한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EmailTemplates"
                ],
                "summary": "이메일 템플릿 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "템플릿 식별자",
                        "name": "template_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailTemplateDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "put": {
                "description": "이메일 템플릿 설정을 업데이트한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EmailTemplates"
                ],
                "summary": "이메일 템플릿 수정",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "템플릿 식별자",
                        "name": "template_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "업데이트할 템플릿 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_request.UpdateEmailTemplate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailTemplateDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "선택된 이메일 템플릿을 삭제한다.",
                "tags": [
                    "EmailTemplates"
                ],
                "summary": "이메일 템플릿 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "템플릿 식별자",
                        "name": "template_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/health-check": {
            "get": {
                "description": "서비스 상태를 반환한다.",
                "tags": [
                    "Health"
                ],
                "summary": "서비스 헬스체크",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/offers": {
            "get": {
                "description": "오퍼 목록과 총 개수를 조회한다.",
                "tags": [
                    "Offers"
                ],
                "summary": "오퍼 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "오퍼 상태 필터",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "페이지 번호",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "페이지당 항목 수",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ListOffersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "새로운 오퍼를 생성한다.",
                "tags": [
                    "Offers"
                ],
                "summary": "오퍼 생성",
                "parameters": [
                    {
                        "description": "오퍼 생성 요청",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_request.CreateOfferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ListOffersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/offers/{offer_id}": {
            "get": {
                "description": "오퍼의 상세 정보와 승인자 목록을 조회한다.",
                "tags": [
                    "Offers"
                ],
                "summary": "오퍼 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "오퍼 식별자",
                        "name": "offer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.OfferDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/offers/{offer_id}/approvals": {
            "get": {
                "description": "오퍼의 승인(결재) 이력 목록을 반환합니다.",
                "tags": [
                    "Approvals"
                ],
                "summary": "오퍼별 승인 이력 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "오퍼 식별자",
                        "name": "offer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ApprovalHistoryItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "오퍼 승인(결재) 요청을 생성한다.",
                "tags": [
                    "Approvals"
                ],
                "summary": "승인 요청 생성",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "오퍼 식별자",
                        "name": "offer_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "승인자 ID 리스트",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_request.CreateApprovalsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ApprovalHistoryItem"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/offers/{offer_id}/approvals/{approval_id}": {
            "put": {
                "description": "오퍼 승인(결재) 요청을 처리한다.",
                "tags": [
                    "Approvals"
                ],
                "summary": "승인 처리",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "승인 요청 식별자",
                        "name": "approval_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "승인 상태 및 코멘트",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_request.ProcessApprovalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ProcessApprovalResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/offers/{offer_id}/send": {
            "post": {
                "description": "오퍼 레터 이메일을 전송하고, 발송 이력을 기록하여 반환한다.",
                "tags": [
                    "Offers"
                ],
                "summary": "오퍼 레터 이메일 전송",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "오퍼 식별자",
                        "name": "offer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.SendOfferEmailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/grid-preferences": {
            "get": {
                "description": "현재 로그인된 사용자의 모든 그리드 설정을 반환한다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GridPreferences"
                ],
                "summary": "그리드 설정 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_preference_dto_response.GridPreference"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "새로운 그리드 설정을 생성한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GridPreferences"
                ],
                "summary": "그리드 설정 생성",
                "parameters": [
                    {
                        "description": "생성할 그리드 설정",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_preference_dto_request.CreateGridPreference"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_preference_dto_response.GridPreference"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/grid-preferences/{preference_id}": {
            "put": {
                "description": "그리드 설정(config)을 업데이트한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GridPreferences"
                ],
                "summary": "그리드 설정 수정",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "설정 식별자",
                        "name": "preference_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "업데이트할 설정 내용",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_preference_dto_request.UpdateGridPreference"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_preference_dto_response.GridPreference"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "선택된 그리드 설정을 삭제한다.",
                "tags": [
                    "GridPreferences"
                ],
                "summary": "그리드 설정 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "설정 식별자",
                        "name": "preference_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_request.BulkUpdateStageRequest": {
            "type": "object",
            "required": [
                "ids",
                "stage"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "reason": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_request.UpdateStageRequest": {
            "type": "object",
            "required": [
                "stage"
            ],
            "properties": {
                "reason": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.ApplicantDetail": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "current_stage": {
                    "type": "string"
                },
                "education": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "experience": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "tech_stack": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.ApplicantItem": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "integer"
                },
                "current_stage": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.BulkUpdateResponse": {
            "type": "object",
            "properties": {
                "updated": {
                    "type": "integer"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.ListApplicantsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.ApplicantItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.StageHistoryItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "history_id": {
                    "type": "integer"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_applicant_dto_response.UpdateStageResponse": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "integer"
                },
                "new_stage": {
                    "type": "string"
                },
                "old_stage": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_request.CreateApprovalsRequest": {
            "type": "object",
            "required": [
                "approver_ids"
            ],
            "properties": {
                "approver_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_request.CreateOfferRequest": {
            "type": "object",
            "required": [
                "application_id",
                "benefits",
                "letter_content",
                "location",
                "position",
                "salary",
                "start_date"
            ],
            "properties": {
                "application_id": {
                    "type": "integer"
                },
                "benefits": {
                    "type": "string"
                },
                "letter_content": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "salary": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_request.ProcessApprovalRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ApprovalHistoryItem": {
            "type": "object",
            "properties": {
                "approval_id": {
                    "type": "integer"
                },
                "approver_id": {
                    "type": "integer"
                },
                "comment": {
                    "type": "string"
                },
                "decided_at": {
                    "type": "string"
                },
                "requested_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ApproverStatus": {
            "type": "object",
            "properties": {
                "approver_id": {
                    "type": "integer"
                },
                "comment": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ListOffersResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.OfferItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.OfferDetail": {
            "type": "object",
            "properties": {
                "approvers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ApproverStatus"
                    }
                },
                "offer_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.OfferItem": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "offer_id": {
                    "type": "integer"
                },
                "position": {
                    "type": "string"
                },
                "salary": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.ProcessApprovalResponse": {
            "type": "object",
            "properties": {
                "approval_id": {
                    "type": "integer"
                },
                "decided_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_offer_dto_response.SendOfferEmailResponse": {
            "type": "object",
            "properties": {
                "email_history_id": {
                    "type": "integer"
                },
                "sent_at": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_preference_dto_request.CreateGridPreference": {
            "type": "object",
            "required": [
                "config",
                "grid_name"
            ],
            "properties": {
                "config": {
                    "description": "설정 데이터",
                    "type": "object",
                    "additionalProperties": true
                },
                "grid_name": {
                    "description": "그리드명",
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_preference_dto_request.UpdateGridPreference": {
            "type": "object",
            "required": [
                "config"
            ],
            "properties": {
                "config": {
                    "description": "설정 데이터",
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_preference_dto_response.GridPreference": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "설정 데이터",
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "description": "생성일",
                    "type": "string"
                },
                "created_by": {
                    "description": "수정자",
                    "type": "string"
                },
                "grid_name": {
                    "description": "그리드명",
                    "type": "string"
                },
                "preference_id": {
                    "description": "설정 ID",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "수정일시 (NULL 허용)",
                    "type": "string"
                },
                "updated_by": {
                    "description": "수정자   (NULL 허용)",
                    "type": "string"
                },
                "user_id": {
                    "description": "유저 ID",
                    "type": "integer"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_request.CreateEmailHistory": {
            "type": "object",
            "required": [
                "body",
                "template_id",
                "title"
            ],
            "properties": {
                "applicant_id": {
                    "type": "integer"
                },
                "body": {
                    "type": "string"
                },
                "offer_id": {
                    "type": "integer"
                },
                "template_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_request.CreateEmailTemplate": {
            "type": "object",
            "required": [
                "config",
                "name"
            ],
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_request.UpdateEmailTemplate": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.CreateEmailHistoryResponse": {
            "type": "object",
            "properties": {
                "email_id": {
                    "type": "integer"
                },
                "sent_at": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailHistoryDetail": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "email_id": {
                    "type": "integer"
                },
                "sent_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailHistoryItem": {
            "type": "object",
            "properties": {
                "email_id": {
                    "type": "integer"
                },
                "sent_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailTemplateDetail": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "template_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_template_dto_response.EmailTemplateItem": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "template_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_HongJungWan_recruit-process-engine-back_internal_user_dto_request.Credentials": {
            "type": "object",
            "required": [
                "login_id",
                "password"
            ],
            "properties": {
                "login_id": {
                    "description": "사용자 이름",
                    "type": "string"
                },
                "password": {
                    "description": "비밀번호",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Recruit Process Engine API",
	Description:      "채용 프로세스 엔진 백엔드 API 문서",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
